### PR TITLE
Provide force_sync to solver schedule methods

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/storages/issues/2308

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Review by pacospace — APPROVED** [review]
lgtm! 💯

**Comment by fridex** [comment]
> @fridex: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> aicoe-ci/prow/pytest	[aa4b7b2](https://github.com/thoth-station/common/commit/aa4b7b23e29153acfca40b0787e73e0597e60125)	[link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/prow-logs/pr-logs/pull/thoth-station_common/1162/thoth-pytest-py38/1399837776827912192)	`/test thoth-pytest-py38`
> [Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=common&pr=1162). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/common/issues?q=is:issue+is:open) when you hit one in your PR.

CC @harshad16 the log cannot be accessed, PTAL

**Pull request merged**
