### PR TITLE
:pushpin: Relock

### PR DESCRIPTION
**Pull request by CermakM**
#550 should be closed and new patch release should be requested after this

Signed-off-by: Marek Cermak <macermak@redhat.com>

### CODE REVIEW

**Comment by CermakM** [comment]
@goern can you close the #550 and request a new patch release, please?

**Comment by goern** [comment]
I think you could have requested a relock from Kebechet, @fridex  ?

**Comment by CermakM** [comment]
I am afraid Kebechet would gracefully ignore me since I am not a maintainer of this repo.

**Comment by goern** [comment]
really?!

**Comment by fridex** [comment]
It relocks automatically if there is an issue or if there is missing lock file in the directory.

**Pull request merged**
