### PR TITLE
Add types-requests to the dev dependencies

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/common/pull/1168#issuecomment-859316285

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by fridex** [comment]
> @fridex: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> aicoe-ci/prow/pytest	[79fc5c6](https://github.com/thoth-station/common/commit/79fc5c6add8aeda8f108eeb974632a05aabbd8e2)	[link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/prow-logs/pr-logs/pull/thoth-station_common/1170/thoth-pytest-py38/1403243549025112064)	`/test thoth-pytest-py38`
> [Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=common&pr=1170). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Afridex). Please help us and [open an issue](https://github.com/thoth-station/common/issues?q=is:issue+is:open) when you hit one in your PR.

CC @goern @harshad16 cannot expand logs here. Any suggestion?

**Comment by goern** [comment]
hmm, right, expanding the build log on the HTML pages sometimes takes a lot of time, esp if its 11k lines, looking at the raw log might be easier/faster, but... http://s3.openshift-storage.svc.cluster.local/ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/prow-logs/pr-logs/pull/thoth-station_common/1170/thoth-pytest-py38/1403243549025112064/build-log.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=mM8HzDK82lqAtKapmwca%2F20210611%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210611T070329Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=0fceafda8995a3a46748c48e238296f48d307082d0a56d41387a872fab826344

@harshad16 I think Prow is putting the wrong URL in for the S3 storage?!

**Comment by harshad16** [comment]
>  I think Prow is putting the wrong URL in for the S3 storage?!

The prow link keeps showing the last iteration till the new iteration takes over. The link would be of the previously run execution, as soon as newer execution get done , it is update.
is there some other reason you feel, it is showing wrong value.

**Comment by harshad16** [comment]
we can close this PR
the types-requests required for mypy error fix was fixed by updating the mypy.ini config by PR #1173 
this update is not needed anymore. @fridex

**Comment by fridex** [comment]
> we can close this PR
> the types-requests required for mypy error fix was fixed by updating the mypy.ini config by PR #1173
> this update is not needed anymore. @fridex

Sounds good. Thanks. 👍🏻 

/close

**Pull request closed without merging**
