### PR TITLE
Add re_run_adviser_id metadata for qeb-hwt app

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

### CODE REVIEW

**Comment by pacospace** [comment]
> Hm, how would the logic look like then?
> 
> Wouldn't be it easier to mark it in the database? In that case, the query for adviser runs that need to be re-run would already incorporate this flag in it and we don't need to iterate (download) results from ceph.

So we schedule the new adviser and we change that flag in the database after scheduling for the adviser run where we took the info?

**Comment by fridex** [comment]
> > Hm, how would the logic look like then?
> > Wouldn't be it easier to mark it in the database? In that case, the query for adviser runs that need to be re-run would already incorporate this flag in it and we don't need to iterate (download) results from ceph.
> 
> So we schedule the new adviser and we change that flag in the database for the adviser run where we took the info, right after scheduling ?

I think so. Otherwise, we would need to go to ceph and load whole JSON results (more expensive than having a binary flag in the database that can be used during the query).

**Comment by pacospace** [comment]
> > > Hm, how would the logic look like then?
> > > Wouldn't be it easier to mark it in the database? In that case, the query for adviser runs that need to be re-run would already incorporate this flag in it and we don't need to iterate (download) results from ceph.
> > 
> > 
> > So we schedule the new adviser and we change that flag in the database for the adviser run where we took the info, right after scheduling ?
> 
> I think so. Otherwise, we would need to go to ceph and load whole JSON results (more expensive than having a binary flag in the database that can be used in the query).

Modified as we discussed in the meeting. Thanks!! :beers:

**Comment by pacospace** [comment]
recheck

**Comment by fridex** [comment]
> * [thoth-pytest ](https://managesf.thoth-station.ninja/zuul/t/local/build/173619d96a614ca086f5712060f9a1f0) : FAILURE in 4m 17s

https://github.com/thoth-station/common/pull/728

**Pull request merged**
