### PR TITLE
Add mypy back to pre-commit

### PR DESCRIPTION
**Pull request by xtuchyna**
## Related Issues and Dependencies
Closes https://github.com/thoth-station/common/issues/1252

## This introduces a breaking change

- [ ] Yes
- [X] No

## Description
SSIA

### CODE REVIEW

**Comment by xtuchyna** [comment]
This should pass pre-commit, basically fixed some type hints to be more ambiguous and some to be ignored, locked `attrs` module to a `v22.1.0` and added it as an additional dependency specifically in `mypy.ini` config file

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve
thanks :100:

**Pull request merged**
