### PR TITLE
Bump black version to 19.10b0

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by goern** [comment]
Uhhh, why is that?

**Comment by fridex** [comment]
> Uhhh, why is that?

I'm getting different results when I format code locally from the ones from CI.

**Comment by goern** [comment]
> > Uhhh, why is that?
> 
> I'm getting different results when I format code locally from the ones from CI.

so we set a policy that we only use black 19.10b0 with all repositories and locally?

**Comment by fridex** [comment]
> > > Uhhh, why is that?
> > 
> > 
> > I'm getting different results when I format code locally from the ones from CI.
> 
> so we set a policy that we only use black 19.10b0 with all repositories and locally?

`19.10b0` is the most recent version now. It might be good idea to keep up with the most recent releases in this case.

**Pull request closed without merging**
