### PR TITLE
Add method to schedule graph-update-schema job

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Related-To: https://github.com/thoth-station/storages/issues/2080

### CODE REVIEW

**Review by fridex — APPROVED** [review]
lgtm :+1:

**Comment by pacospace** [comment]
I cannot reproduce failed pytest locally @harshad16

**Comment by harshad16** [comment]
> I cannot reproduce failed pytest locally.
i will have a look at this

**Pull request merged**
