### PR TITLE
Remove underscores from repository name [mi-scheduler workflow naming]

### PR DESCRIPTION
**Pull request by xtuchyna**
## Related Issues and Dependencies
Related to https://github.com/thoth-station/mi-scheduler/issues/249

## This introduces a breaking change

- [ ] Yes
- [X] No

## Description
SSIA

### CODE REVIEW

**Review by mayaCostantini — APPROVED** [review]
lgtm :+1:

**Comment by mayaCostantini** [comment]
@xtuchyna just some pre-commit issue to fix and this is good to go

**Comment by xtuchyna** [comment]
sup @mayaCostantini the bot needs lgtm again :eyes:

**Pull request merged**
