### PR TITLE
Move normalization functions to helpers

### PR DESCRIPTION
**Pull request by fridex**
## This introduces a breaking change

- [x] No

Related: https://github.com/thoth-station/thamos/issues/652

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
lgtm, 
just need pre-commit run fix.

**Comment by fridex** [comment]
> just need pre-commit run fix.

I updated pre-commit in #1061 which should solve the issue. I'll merge it and rebase this one so things should be ok. :+1:

**Review by harshad16 — APPROVED** [review]
lgtm :+1:

**Pull request merged**
