### PR TITLE
Updated randbits to fix #568

### PR DESCRIPTION
**Pull request by CermakM**
Signed-off-by: Marek Cermak <macermak@redhat.com>

modified:   thoth/common/openshift.py

### CODE REVIEW

**Comment by goern** [comment]
whats the rational for this change?

**Comment by goern** [comment]
whats the rational of this change?

**Comment by CermakM** [comment]
Sorry :/ Was not aware it worked like that in the #568

**Comment by CermakM** [comment]
Rational can be found there.

**Pull request merged**
