### PR TITLE
Make all datetimes timezone aware

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
A hotfix..

**Comment by goern** [comment]
why is everything in UTC not good enough?

**Comment by fridex** [comment]
> why is everything in UTC not good enough?

This query [1] used for checking if the given document was already synced fails due to timezone issues - when computing timestamp, there are issues with timezone not being set.

[1] https://github.com/thoth-station/storages/blob/master/thoth/storages/graph/janusgraph.py#L386

**Comment by fridex** [comment]
@goern I will merge this to check it in the cluster

**Pull request merged**
