### PR TITLE
add enum for internal triggers

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

thoth-station/kebechet#584

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Create an enum representing the different internal triggers

### CODE REVIEW

**Review by fridex — COMMENTED** [review]
Looks good to me :+1: :1st_place_medal:

**Comment by KPostOffice** [comment]
> Looks good to me +1 1st_place_medal

Should I add one more line:
`NONE = auto()`
or in the case of no justification should we just use python's `None`?

**Comment by pacospace** [comment]
> > Looks good to me +1 1st_place_medal
> 
> Should I add one more line:
> `NONE = auto()`
> or in the case of no justification should we just use python's `None`?

is there a case where the internal trigger run without a justification?

**Comment by KPostOffice** [comment]
I don't think internal triggers should be sent without this justification, but this is metadata that will be part of `kebechet-administrator-trigger` message.  At that point anything could technically send a `kebechet-adminstrator` message I guess? though I feel like `kebechet-admin` will probably only be used for multiplexing internal triggers to schedule Kebechet for each repo so it should always have this metadata set.  I will leave this as is.

**Review by fridex — APPROVED** [review]
lgtm, thanks! :100:

**Review by harshad16 — APPROVED** [review]
lgtm :+1:

**Pull request merged**
