### PR TITLE
bump python version

### PR DESCRIPTION
**Pull request by bissenbay**
Related-To: https://github.com/thoth-station/thoth-application/issues/545#issuecomment-735908736

### CODE REVIEW

**Review by fridex — APPROVED** [review]
:ship: 

thanks!

**Comment by bissenbay** [comment]
@harshad16 PTAL https://github.com/thoth-station/common/pull/1050/commits/46c64cb1931ea6a57318a9515b5819a4ec9b164d

**Review by harshad16 — APPROVED** [review]
lgtm , thanks :100:

**Comment by fridex** [comment]
I will merge this manually, let's see if the issue persists on Python 3.8

**Pull request merged**
